CREATE TABLE [dbo].[FactOrderDetails](
    [OrderDetailKey] [int] IDENTITY(1,1) NOT NULL,
    [CustomerKey] [int] NOT NULL,
    [ProductKey] [int] NOT NULL,
    [EmployeeKey] [int] NOT NULL,
    [ShipperKey] [int] NOT NULL,
    [OrderDateKey] [int] NOT NULL,
    [RequiredDateKey] [int] NOT NULL,
    [ShippedDateKey] [int] NOT NULL,
    [Quantity] [smallint] NOT NULL,
    [UnitPrice] [money] NOT NULL,
    [Discount] [real] NOT NULL,
    [ExtendedAmount] AS (CONVERT([money], ([Quantity] * [UnitPrice]) * (1 - [Discount]))),
    [Freight] [money] NOT NULL,
    [RowCreatedDate] [datetime] NOT NULL CONSTRAINT [DF_FactOrderDetails_RowCreatedDate] DEFAULT (GETDATE()),
    CONSTRAINT [PK_FactOrderDetails] PRIMARY KEY CLUSTERED ([OrderDetailKey] ASC),
    CONSTRAINT [FK_Fact_Customer] FOREIGN KEY ([CustomerKey]) REFERENCES [dbo].[DimCustomer] ([CustomerKey]),
    CONSTRAINT [FK_Fact_Product] FOREIGN KEY ([ProductKey]) REFERENCES [dbo].[DimProduct] ([ProductKey]),
    CONSTRAINT [FK_Fact_Employee] FOREIGN KEY ([EmployeeKey]) REFERENCES [dbo].[DimEmployee] ([EmployeeKey]),
    CONSTRAINT [FK_Fact_Shipper] FOREIGN KEY ([ShipperKey]) REFERENCES [dbo].[DimShipper] ([ShipperKey]),
    CONSTRAINT [FK_Fact_OrderDate] FOREIGN KEY ([OrderDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_Fact_RequiredDate] FOREIGN KEY ([RequiredDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_Fact_ShippedDate] FOREIGN KEY ([ShippedDateKey]) REFERENCES [dbo].[DimDate] ([DateKey])
);